= Introducing the New bGC(2) Site
:hp-image: https://lh3.googleusercontent.com/ORoECpNWjVc7MILpWSs6AUliZYEFsW-VIOL8Ghts6e56vCxqP8pMYJ6woARqCcU7w2Zr-83vUc6gry0Tfi9BsCFUd-kA0UpRL1ApzPE05l3V-ovLGnX0ifx0mzLadySEuXaljgxpnaqKsQfGGHdttHeICfrdm2d1vhkfx6B7w-kKFHofWzErkYJqoSGMtZU0OSqpx7WZFdwzx2nPSOD30g45eTKUTHpROzlh9BEpeE-Lhm2a9TaKuiMQv4ppnWfG4Nlh_5q__PQrC_ajxHf-be29Hq6mmfbq5cLfSOMaVV27yE8ZhnhJYa15kEcaRolqWgF-ax50-8HXntiGGIgr-WfYkBu-QohwG8D3WnKb9w8KtFLK0_HF_xqZ8Wtg8-f6dXedEniEUEG-qWTIwvU4I5Mv9jyKrBwxPVF4G8HxoLd-uhD33M13cT-KETVT2rL7zSDI0J0D9bHZEemO8Y6JBk8B1YzH2T1t2tJ1wHSL3DTK_xd6LaAFlBLFC1M2thsUyd1swbkBvIR3HFOmuWHMhcMl3_z7S425IPv8bW7nfmJSVQfJEUlFPf-jEwnbgukFg0sn=w872-h657-no
:hp-tags: blackGirlsCode, web design, Bootsrap

I am pleased to announce the redesign of the link:blackgirlscode.github.io[GC(2)] site!  This is something long overdue and I am very excited about it's development.  It is almost night and day to the previous version and it is a testament of my growth as a developer.  When I first took on this project, it took about three weeks and riddled with errors.  I kept seeing this "clearfix" class thrown about and had no clue as to it's purpose; so I just deleted it.  (Happy to say now I know whats it's for.)  Plus, I used a template that was poor in design and poorly documented.

Using Bootstrap was neccesary to build, as well as a few jQuery Plugins.  I feel at times, both are used when a simple boilerplate and Vanilla Javascript would suffice.  I myself felt lazy using it to develop a website;  but it was neccessary to achieve the big picture results I see for the organization.  Plus time-savings had to to be considered; this week I am getting my hands dirty test-driving my link:https:codeschool.com[CodeSchool] subscription that was gifted for Christmas.  

There still are things I'd like to add such as a schedule of events and the curriculum section for members, but at least for now it is not such an e̶m̶b̶a̶r̶r̶a̶s̶m̶e̶n̶t̶ eye-sore. 

Features are included that, before, I did not have the know-how to complete. Simple things like an image carousel, a fixed/collapsed navigation bar, some cool transitions, member profiles and testimonials, etc.   

More to come on this, but so far, so good!